const express = require('express');
const router = express.Router();
const {getStores, getStoreBySlug, getStoresByTag, resize, createStore, updateStore, addStore, editStore, upload} = require('../controllers/storeController');
const { catchErrors } = require('../handlers/errorHandlers');
const {loginForm, userRegister, validateRegister, register} = require('../controllers/userController');
const {login, logout} = require('../controllers/authController');

router.get('/', catchErrors(getStores));
router.get('/stores', catchErrors(getStores));
router.get('/add', addStore);
router.post('/add',  upload, catchErrors(resize), catchErrors(createStore));
router.post('/add/:id', upload, catchErrors(resize), catchErrors(updateStore));
router.get('/stores/:id/edit', catchErrors(editStore));
router.get('/store/:slug', catchErrors(getStoreBySlug));
router.get('/tags', catchErrors(getStoresByTag));
router.get('/tags/:tag', catchErrors(getStoresByTag));
router.get('/login', loginForm );
router.get('/register', userRegister);
router.post('/register', validateRegister, register, login);
router.get('/logout', logout);
module.exports = router;
